import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e3e2e7",
        "on-background": "#1a1b1f",
        "primary-fixed-dim": "#afc6ff",
        "on-primary-fixed": "#001a43",
        "on-secondary-fixed": "#261900",
        "surface-container-highest": "#e3e2e7",
        "surface-container-low": "#f4f3f8",
        "surface-tint": "#465e90",
        "surface-container-high": "#e9e7ec",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#785a1a",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#474746",
        "error": "#ba1a1a",
        "surface-bright": "#faf8fd",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#e5e2e1",
        "surface": "#faf8fd",
        "surface-dim": "#dbd9de",
        "on-secondary-fixed-variant": "#5d4201",
        "primary": "#00163c",
        "secondary": "#775a19",
        "on-tertiary-fixed": "#1c1b1b",
        "tertiary-fixed-dim": "#c8c6c5",
        "primary-fixed": "#d9e2ff",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#2d4677",
        "on-surface-variant": "#44474f",
        "secondary-fixed": "#ffdea5",
        "inverse-primary": "#afc6ff",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#969494",
        "surface-container": "#efedf2",
        "primary-container": "#0f2b5b",
        "inverse-on-surface": "#f2f0f5",
        "tertiary-container": "#2d2d2d",
        "on-surface": "#1a1b1f",
        "outline-variant": "#c4c6d0",
        "on-primary-container": "#7c94ca",
        "inverse-surface": "#2f3034",
        "tertiary": "#181818",
        "background": "#faf8fd",
        "secondary-container": "#fed488",
        "outline": "#747780",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#e9c176",
        "gold": "#775a19",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "24px",
        "container-max": "1280px",
        "margin-edge": "48px",
        "stack-sm": "16px",
        unit: "8px",
        "section-gap": "120px",
        "stack-md": "32px",
      },
      fontFamily: {
        serif: ["Noto Serif", "serif"],
        sans: ["Manrope", "sans-serif"],
        "headline-lg": ["Noto Serif"],
        "display-xl": ["Noto Serif"],
        "headline-md": ["Noto Serif"],
        "body-md": ["Manrope"],
        "label-caps": ["Manrope"],
        "body-lg": ["Manrope"],
      },
      fontSize: {
        "headline-lg": ["40px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-xl": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["28px", { lineHeight: "1.3", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
export default config;
